#    Copyright (C) 2025  nghfp9wa7bzq@gmail.com

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

services:
  db:
    build:
      context: db
      secrets:
        - db-user-password
        - db-root-password
      args:
        - DB_USER_PASSWORD_FILE=/run/secrets/db-user-password
        - DOCKER_USER_NAME=docker
        - DOCKER_DB_NAME=dockerdb
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-root-password)" --silent',
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    # This is referenced in the settings.php file.
    hostname: mysql
    expose:
      - 3306
      - 33060
    # Use this for dev only!
    # ports:
    #   - "3306:3306"

  php:
    build:
      context: php
      # secrets:
      #   - frontend-root-password
      #   - frontend-user-password
      # args:
      #   - DOCKER_ROOT_PASSWD_FILE=/run/secrets/frontend-root-password
      #   - DOCKER_USER_UID=1000
      #   - DOCKER_USER_NAME=docker
      #   - DOCKER_USER_PASSWD_FILE=/run/secrets/frontend-user-password
    # shm_size: '256m'
    restart: always
    # working_dir: /app
    volumes:
      - ./app:/usr/share/nginx/html:ro
    environment:
      - DB_USER_PASSWORD_FILE=/run/secrets/db-user-password
    secrets:
      - db-user-password
    networks:
      - backnet
    # This is referenced in the nginx config file.
    hostname: php
    # expose php-fpm to docker network
    expose:
      - 9000
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: "ghcr.io/nginxinc/nginx-unprivileged:latest"
    restart: always
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    networks:
      - backnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - backnet
    depends_on:
      db:
        condition: service_healthy
    # profiles:
    #   - debug

volumes:
  db-data:

secrets:
  db-root-password:
    file: secrets/db_root_password.txt
  db-user-password:
    file: secrets/db_user_password.txt
  frontend-root-password:
    file: secrets/frontend_root_password.txt
  frontend-user-password:
    file: secrets/frontend_user_password.txt

networks:
  backnet:
